#ifndef STATS_HPP_INCLUDED
#define STATS_HPP_INCLUDED

#include"dir_explore/str_array.h"
typedef struct{
    unsigned short processCodeValuePair:1;
    unsigned short endSection:1;
    unsigned short addLayer:1;
    unsigned short addLinetype:1;
    unsigned short addLinetypeDash:1;
    unsigned short addBlock:1;
    unsigned short endBlock:1;
    unsigned short addTextStyle:1;
    unsigned short addPoint:1;
    unsigned short addLine:1;
    unsigned short addXLine:1;
    unsigned short addRay:1;
    unsigned short addArc:1;
    unsigned short addCircle:1;
    unsigned short addEllipse:1;
    unsigned short addPolyline:1;
    unsigned short addVertex:1;
    unsigned short addSpline:1;
    unsigned short addControlPoint:1;
    unsigned short addFitPoint:1;
    unsigned short addKnot:1;
    unsigned short addInsert:1;
    unsigned short addTrace:1;
    unsigned short add3dFace:1;
    unsigned short addSolid:1;
    unsigned short addMText:1;
    unsigned short addMTextChunk:1;
    unsigned short addText:1;
    unsigned short addArcAlignedText:1;
    unsigned short addAttribute:1;
    unsigned short addDimAlign:1;
    unsigned short addDimLinear:1;
    unsigned short addDimRadial:1;
    unsigned short addDimDiametric:1;
    unsigned short addDimAngular:1;
    unsigned short addDimAngular3P:1;
    unsigned short addDimOrdinate:1;
    unsigned short addLeader:1;
    unsigned short addLeaderVertex:1;
    unsigned short addHatch:1;
    unsigned short addImage:1;
    unsigned short linkImage:1;
    unsigned short addHatchLoop:1;
    unsigned short addHatchEdge:1;
    unsigned short addXRecord:1;
    unsigned short addXRecordString:1;
    unsigned short addXRecordReal:1;
    unsigned short addXRecordInt:1;
    unsigned short addXRecordBool:1;
    unsigned short addXDataApp:1;
    unsigned short addXDataString:1;
    unsigned short addXDataReal:1;
    unsigned short addXDataInt:1;
    unsigned short addDictionary:1;
    unsigned short addDictionaryEntry:1;
    unsigned short endEntity:1;
    unsigned short addComment:1;
    unsigned short setVariableVector:1;
    unsigned short setVariableString:1;
    unsigned short setVariableInt:1;
    unsigned short setVariableDouble:1;
    unsigned short endSequence:1;
}dxf_handler_funcions;

class stats
{
    int processCodeValuePair_count=0;
    int endSection_count=0;
    int addLayer_count=0;
    int addLinetype_count=0;
    int addLinetypeDash_count=0;
    int addBlock_count=0;
    int endBlock_count=0;
    int addTextStyle_count=0;
    int addPoint_count=0;
    int addLine_count=0;
    int addXLine_count=0;
    int addRay_count=0;
    int addArc_count=0;
    int addCircle_count=0;
    int addEllipse_count=0;
    int addPolyline_count=0;
    int addVertex_count=0;
    int addSpline_count=0;
    int addControlPoint_count=0;
    int addFitPoint_count=0;
    int addKnot_count=0;
    int addInsert_count=0;
    int addTrace_count=0;
    int add3dFace_count=0;
    int addSolid_count=0;
    int addMText_count=0;
    int addMTextChunk_count=0;
    int addText_count=0;
    int addArcAlignedText_count=0;
    int addAttribute_count=0;
    int addDimAlign_count=0;
    int addDimLinear_count=0;
    int addDimRadial_count=0;
    int addDimDiametric_count=0;
    int addDimAngular_count=0;
    int addDimAngular3P_count=0;
    int addDimOrdinate_count=0;
    int addLeader_count=0;
    int addLeaderVertex_count=0;
    int addHatch_count=0;
    int addImage_count=0;
    int linkImage_count=0;
    int addHatchLoop_count=0;
    int addHatchEdge_count=0;
    int addXRecord_count=0;
    int addXRecordString_count=0;
    int addXRecordReal_count=0;
    int addXRecordInt_count=0;
    int addXRecordBool_count=0;
    int addXDataApp_count=0;
    int addXDataString_count=0;
    int addXDataReal_count=0;
    int addXDataInt_count=0;
    int addDictionary_count=0;
    int addDictionaryEntry_count=0;
    int endEntity_count=0;
    int addComment_count=0;
    int setVariableVector_count=0;
    int setVariableString_count=0;
    int setVariableInt_count=0;
    int setVariableDouble_count=0;
    int endSequence_count=0;
    public:
    void evaluate_dxf_stats(dxf_handler_funcions flags);
    void print_stat(void);
};


#endif // STATS_HPP_INCLUDED
